#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 28 14:10:24 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}